services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
    command: |
      sh -c "
      chmod -R 777 /var/www &&
      php artisan config:clear &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  react:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ./webapp:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - api

volumes:
  mysql_data:
